name: CI - TaskIO Pipeline

on:
  push:
    branches: [ "main", "master", "feature/**", "feat/**" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-application:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx pytest pytest-asyncio aiosqlite

    - name: Executar Testes com Pytest
      env:
        SECRET_KEY: "7XhqRHE4Dv"
        DATABASE_URL: "sqlite+aiosqlite:///:memory:"
      run: |
        pytest -v